from sg import *
import re

t = read("manuscript_uzb.html")
P = R["pairs"]; S_ = R["pbs"]; E = R["eth"]; NN = R["nnls_mix"]; MT = R["mix_test"]; U = R["ue_dist"]


def after(t, heading_regex, new_p, tag="p"):
    m = re.search(heading_regex, t)
    assert m, heading_regex
    i = t.index("<p>", m.end()); j = t.index("</p>", i) + 4
    return t[:i] + "<p>\n    " + new_p + "\n</p>" + t[j:]


fst = lambda k: f"{P[k]['weighted_all']:.4f}"
t = t.replace("admixture, low inbreeding, and selection signatures at immune and metabolic loci", "European, South Asian and East Asian ancestry and low inbreeding in an array-based population-genetic survey")
# ---- abstract
t = after(t, r"<h4>Methods</h4>",
          "We analysed an expanded cohort of 1,256 quality-controlled, imputed Uzbek samples (custom Illumina array, imputed against TOPMed r2) together with 2,712 reference samples (EUR, EAS, SAS, AFR) of the 1000 Genomes high-coverage (NYGC 30x, GRCh38) release. We ran principal component analysis, ADMIXTURE (K=2&ndash;8), pairwise Weir &amp; Cockerham F<sub>ST</sub> for all ten population pairs, classical multidimensional scaling, the Population Branch Statistic (PBS), runs-of-homozygosity analysis and relatedness estimation. Findings were cross-checked with independent calculations (allele-frequency mixture fit, unascertained-SNP F<sub>ST</sub> on chromosome 22, permutation and positive controls).")
t = after(t, r"<h4>Results</h4>",
          f"Uzbeks form a cline between European, South Asian and East Asian reference groups. Weighted F<sub>ST</sub> was {fst('SAS_UZB')} against SAS, {fst('EUR_UZB')} against EUR, {fst('EAS_UZB')} against EAS and {fst('AFR_UZB')} against AFR. At ADMIXTURE K=4 the Uzbek cohort was on average about 50% EUR-like, 30% EAS-like and 19% SAS-like (an allele-frequency mixture fit gave {NN['EUR'] * 100:.0f}/{NN['EAS'] * 100:.0f}/{NN['SAS'] * 100:.0f}%); cross-validation error had no clear minimum, and at K=7 about half of the Uzbek ancestry formed a component absent from every reference. Self-reported ethnicity and birthplace were significantly associated with ancestry. A PBS scan of {S_['n']:,} SNPs found no candidate (maximum PBS<sub>UZB</sub> {S_['max']:.3f}; Tier 1 requires 0.3), so no population-specific selection signal is supported in this panel. Median F<sub>ROH</sub> was 0.0147, with 35 of 1,256 individuals above 0.0625; 0.078% of pairs exceeded PI_HAT 0.0884.")
t = after(t, r"<h4>Conclusion</h4>",
          "This work provides a medium-scale, openly described autosomal reference for Uzbeks, locates the cohort relative to global reference groups, and documents that an LD-pruned array panel does not support population-specific selection candidates. It also reports the limits of the approach (no Central Asian reference groups, array ascertainment of the SNP panel).")
# ---- aims
t = t.replace("Provide a publicly described 1,047-sample autosomal reference", "Provide a publicly described autosomal reference of 1,256 Uzbek samples")
t = t.replace("Identify population-specific selection signatures using PBS with EUR + EAS outgroups.", "Test for population-specific selection signatures using PBS with EUR + EAS outgroups (result: none supported).")
# ---- methods
t = after(t, r"<h3>2\.4\. Reference panel merging</h3>",
          "Uzbek variants were intersected by chromosomal position and alleles with the 1000 Genomes high-coverage NYGC GRCh38 reference (3,202 samples, md5-verified; EUR, EAS, SAS and AFR used, 2,712 samples; AMR not used), restricted to biallelic SNPs, and LD-pruned (PLINK <code>--indep-pairwise 50 5 0.2</code>, long-range LD regions removed) yielding 82,744 SNPs shared with the Uzbek data for F<sub>ST</sub>, 64,959 for ADMIXTURE and PCA, and 74,171 after excluding 8,573 sites with an overlapping indel, multiallelic or structural-variant record for per-SNP F<sub>ST</sub> and PBS.")
t = after(t, r"<h3>2\.5\. PCA &amp; ADMIXTURE</h3>",
          "PCA used PLINK 1.9 <code>--pca 20</code> on the 64,959-SNP merged data set (3,968 samples). ADMIXTURE 1.3 was run for K=2&ndash;8 with 5-fold cross-validation and 2 independent seeds. Component names were assigned from the mean membership of the reference superpopulations. Associations with self-reported nationality and birthplace were tested by Kruskal&ndash;Wallis with sample-ID-keyed joins, a label-permutation control and a positive control on the reference labels.")
t = after(t, r"<h3>2\.6\. F<sub>ST</sub> &amp; MDS</h3>",
          "Pairwise Weir &amp; Cockerham F<sub>ST</sub> (PLINK 1.9 <code>--fst --within</code>) was estimated for all ten pairs among five populations (UZB, EUR, EAS, SAS, AFR); the leave-one-chromosome-out jackknife standard error of the mean per-SNP value was computed; classical MDS in two dimensions was computed on the F<sub>ST</sub> matrix. As an independent check, F<sub>ST</sub> was recomputed on chromosome 22 from all common biallelic SNVs (PLINK for reference pairs, Hudson&rsquo;s estimator from allele frequencies for the Uzbek pairs).")
t = after(t, r"<h3>2\.7\. PBS &amp; functional annotation</h3>",
          "PBS (Yi et al. 2010) was computed with EUR and EAS as outgroups, treating Uzbek as the focal branch, with Tier 1 defined as PBS &ge; 0.3, Tier 2 as a minimum allele-frequency difference of 0.3 to every reference group and Tier 3 as near-private alleles. The highest-ranking SNPs were annotated by Ensembl overlap and variant lookup and by GWAS Catalog queries. A non-negative least-squares fit of Uzbek allele frequencies as a mixture of the references tested whether top-ranking SNPs are explained by admixture.")
# ---- results
t = after(t, r"<h3>3\.2\. PCA &amp; global F<sub>ST</sub></h3>",
          f"In the global PCA the first three components carry the structure (eigenvalues 214, 91, 29, then a plateau); PC1 separates AFR, PC2 separates EUR from EAS, and the Uzbek samples form a band along the EUR&ndash;SAS&ndash;EAS axis centred near SAS. Pairwise F<sub>ST</sub> places UZB closest to SAS ({fst('SAS_UZB')}) and EUR ({fst('EUR_UZB')}), then EAS ({fst('EAS_UZB')}) and AFR ({fst('AFR_UZB')}); the UZB&ndash;EAS distance is less than half of EUR&ndash;EAS ({fst('EAS_EUR')}). The ranking is unchanged on chromosome 22 using all common SNVs, although the absolute values of the array-based panel are smaller between Eurasian groups (for example EUR&ndash;EAS 0.087 vs 0.104), an effect of SNP ascertainment.")
t = after(t, r"<h3>3\.3\. ADMIXTURE</h3>",
          "Cross-validation error fell from 0.337 (K=2) to 0.322 (K=4) and then plateaued (0.3213&ndash;0.3219 for K=5&ndash;8); there is no clear minimum. At K=4 the reference superpopulations are almost pure (EUR 0.97, EAS 1.00, SAS 0.89, AFR 0.96) and the Uzbek cohort averages 0.50 EUR-like, 0.30 EAS-like, 0.19 SAS-like and 0.00 AFR-like. At K=7 about half of the Uzbek ancestry forms a component that no reference group carries, so the three-way description depends on K and on the reference panel (which has no Central Asian groups). Self-reported ethnicity (Kruskal&ndash;Wallis p &lt; 10<sup>&minus;40</sup> for each component, with a permuted-label control behaving as expected) and birthplace among self-reported Uzbeks (p &lt; 10<sup>&minus;15</sup>) are associated with ancestry, but regional differences are small in absolute terms (regional mean EUR-like share 0.44&ndash;0.54).")
t = after(t, r"<h3>3\.4\. PBS selection candidates</h3>",
          f"No SNP reached any tier. Of {S_['n']:,} SNPs, the maximum PBS<sub>UZB</sub> was {S_['max']:.3f} (mean {S_['mean']:.3f}, SD {S_['sd']:.3f}), which is where the bulk of the distribution places the maximum of that many values; the largest minimum allele-frequency difference to any reference group was {S_['maxdaf']:.2f}. The 30 most differentiated SNPs between UZB and EUR all have Uzbek frequencies between the EUR and EAS values and are predicted by an admixture mixture model (r = {MT['r_all']:.3f} over all SNPs), i.e. they are ancestry-informative rather than selection signals. Earlier candidate lists (8 Tier 1 SNPs; a relaxed set of 490 enriched for HLA/MHC) came from batch-dependent genotypes in an older reference file and from extraction artefacts at indel-overlapping sites, and are withdrawn.")
t = t.replace("[Insert Fig. 5: PBS Manhattan; Table 2: top 8 PBS candidates with annotation]", "[Insert Fig. 5: PBS Manhattan (site step 10); Table 2: highest PBS values with annotation (site step 12) &mdash; no candidates]")
t = after(t, r"<h3>3\.5\. ROH &amp; relatedness</h3>",
          "44,938 ROH segments &ge; 1 Mb were detected across 1,256 individuals; median F<sub>ROH</sub> was 0.0147 (mean 0.0188) and 35 individuals (2.8%) had F<sub>ROH</sub> above 0.0625. F<sub>ROH</sub> was weakly related to ancestry (Spearman &rho; = &minus;0.17 with the EUR-like and +0.17 with the EAS-like component). PI_HAT &gt; 0.0884 was observed for 613 of 788,140 pairs (0.078%), 11 of them at second degree or closer, supporting the use of a nearly unrelated sample for GWAS. In a pre-QC merged array data set, PI_HAT-based relatedness lists were dominated by five poor-quality samples that are not in the final cohort.")
# ---- discussion
t = after(t, r"<h3>4\.1\. Position of Uzbeks in global variation</h3>",
          "The F<sub>ST</sub> estimates and admixture proportions reproduce the East&ndash;West gradient described in earlier sparse-marker studies (Yunusbayev et al. 2012; Jeong et al. 2019). Uzbeks are about equally close to South Asians and Europeans and clearly closer to East Asians than either of those groups is; which of SAS or EUR is closer is within the uncertainty of the panel and not a finding. Links to Indo-Iranian gene flow (Narasimhan et al. 2019) are plausible context but were not tested: the reference panel has no ancient or Central Asian samples.")
t = after(t, r"<h3>4\.2\. Selection signatures</h3>",
          "This array-based scan does not support population-specific selection in the Uzbek lineage. The panel is sparse (about 74,000 LD-pruned SNPs) and PBS is least sensitive for an admixed focal population, whose frequencies sit between those of its outgroups, so absence of a signal here is not evidence of absence. SNPs that rank highest by F<sub>ST</sub> (including known pigmentation loci such as <em>OCA2</em>) are explained by the European/East Asian ancestry mixture. A selection analysis that models admixture, ideally on sequence data, is the logical follow-up.")
t = after(t, r"<h3>4\.3\. Endogamy</h3>",
          "Median F<sub>ROH</sub> of 0.0147 is almost unchanged between the original and the expanded cohort, with a tail of 35 individuals above 0.0625 (parents at least first cousins in expectation). No pedigree or marriage data were analysed, so the tail is not attributed to endogamous customs. F<sub>ROH</sub> weakly tracks ancestry, which should be modelled alongside it in downstream analyses; geographic stratification of F<sub>ROH</sub> within Uzbekistan was not tested.")
t = t.replace("1,047-sample LD-pruned PLINK BFILE for population genomic re-use (controlled access).", "LD-pruned PLINK BFILE of the 1,256-sample cohort for population genomic re-use (controlled access).")
t = t.replace("Single-array genotyping introduces ascertainment bias;", "Single-array genotyping introduces ascertainment bias (measured here: array-based F<sub>ST</sub> between Eurasian groups is about 15% smaller than on all common SNVs);")
t = banner(t, "<strong>Updated 2026-10-04:</strong> the analysis sections of this draft were rewritten on the NYGC 30x reference. The PBS-candidate and &ldquo;490 HLA candidates&rdquo; claims are withdrawn. The cohort-flow numbers in sections 2.2&ndash;2.3 and 3.1 (1,247 genotyped, 1,074, 1,047) still describe the original cohort and must be replaced by the expanded-cohort flow (see <a href=\"steps/cohorts_and_sample_sets.html\">cohorts and sample sets</a>) before submission. <a href=\"steps/deprecated_old_runs.html\">Current and deprecated runs</a>.")
write("manuscript_uzb.html", t)
print("ms_uzb ok")
