from sg import *

t = read("steps/next_steps.html")
S_ = R["pbs"]
rows = [
    ["Selection scan (PBS) on the NYGC reference", "<span style='color:#065f46;font-weight:600'>CLOSED</span>", f"No Tier 1&ndash;3 SNP; maximum PBS {S_['max']:.3f}. The earlier candidates were reference-file artefacts. <a href='step10.html'>step 10</a>, <a href='step10_pbs_candidates.html'>candidates</a>. The planned &ldquo;check the two undetermined PBS sites on a second array&rdquo; is moot."],
    ["Annotation of the highest-ranking SNPs", "<span style='color:#065f46;font-weight:600'>DONE</span>", "Ensembl and GWAS Catalog lookups with a positive-control gate; none is a selection finding. <a href='step12.html'>step 12</a>"],
    ["Selection analysis that models admixture", "OPEN", "PBS is least sensitive for an admixed focal population (<a href='step10.html'>step 10</a>, limitations). A local-ancestry-aware method on sequence data would be the next scan; not started."],
    ["Pages rebuilt on the new dataset", "<span style='color:#065f46;font-weight:600'>DONE 2026-10-04</span>", "Steps 8, 9, 10, 11 (added section), 12, 13, 14, 15 (section 7), relatedness page, both manuscripts; <a href='deprecated_old_runs.html'>list</a>. Method and oracle checks: <code>scripts/nygc_site_2026-10-04/README.md</code>."],
    ["Final report and presentation figures", "PARTLY DONE", "Report: figures 24, 25 replaced, new figures 27a, 29a and new paragraphs. Deck: slides 6, 10, 11 replaced. Old figures remain in deck slides 3&ndash;5, 7, 9 and in the report outside these sections."],
    ["RelateAdmix / PC-Relate on the NYGC ancestry", "<span style='color:#065f46;font-weight:600'>CLOSED</span>", "Neither used the deprecated global run (RelateAdmix takes ancestry from an ADMIXTURE run on the merged data itself), so no re-run is needed. The ancestry-distance analysis was recomputed on projected K=4 and its conclusion revised: five poor-quality samples dominate the PI_HAT-only discordance. <a href='admixture_aware_relatedness.html'>page</a>"],
    ["LD decay on the new reference", "<span style='color:#065f46;font-weight:600'>DONE</span>", "<a href='step13.html'>step 13</a>: no excess long-range LD in the Uzbek cohort relative to EUR/SAS."],
    ["Site audit (orphaned pages, broken links)", "<span style='color:#065f46;font-weight:600'>DONE</span>", "28 unlinked pages indexed and bannered, broken links repaired, two page-script errors fixed. <a href='archive/index.html'>archive index</a>. 69 loose root files listed, not moved (owner decision)."],
    ["V2 data in DRAGEN /home", "<span style='color:#065f46;font-weight:600'>DONE</span>", "Moved to /staging/ALSU-analysis/spring2026/full_expanded_cohort/alsu_v2 after a byte, count and checksum check; symlink left at the old path."],
    ["Central Asian reference populations (Kazakh GSA, 224 samples, EVA PRJEB89820)", "<span style='color:#92400e;font-weight:600'>IN PROGRESS, not completed</span>", "Data downloaded to DRAGEN; merge pipeline (liftover GRCh37&rarr;38, allele harmonisation, QC, merge with the NYGC + Uzbek panel) was toy-tested on 40 samples (34,661 shared SNPs). The full run, PCA, ADMIXTURE K=2&ndash;8 and F<sub>ST</sub> UZB&ndash;KAZ were interrupted by a server outage (hardware CPU fault, 2026-10-07) and have not been run. This would address the main limitation (no Central Asian reference). HGDP Central Asian populations (gnomAD HGDP+1KG) remain a second option."],
    ["Recent effective population size Ne(t)", "<span style='color:#92400e;font-weight:600'>IN PROGRESS, not completed</span>", "Plan: hap-ibd + IBDNe on the phased imputed data (1,245 samples after removing second-degree relatives, MAF &ge; 0.05). Tools and genetic maps are in place and hap-ibd ran on chr22 as a toy test; the genome-wide run has not been done. IBDNe assumes random mating, so an admixed cohort will give a biased Ne; the result would be read qualitatively. Divergence times between populations cannot be estimated from array/imputed data and will be closed as not feasible with this data once Ne(t) is done. The older ARG pilot (chr22, default CEU demography) is a method demonstration only. <a href='arg_methods_pilot.html'>ARG pilot</a>"],
    ["Provenance of the sample inside the African cluster (code 03-84)", "OPEN (needs the sample sheet)", "PCA position and ADMIXTURE AFR component 0.90; not excluded anywhere. <a href='step8.html'>step 8</a>"],
    ["Re-check of the original array QC cut-off (20% missing genotypes)", "OPEN", "Five samples with 11&ndash;18% missingness and excess heterozygosity passed it and distorted PI_HAT lists in the pre-QC merged set; the final cohort excludes them. <a href='admixture_aware_relatedness.html'>page</a>"],
    ["RPL GWAS items (sections 4&ndash;6 below)", "unchanged, lower priority", "Tier 1 (PBS candidates) is withdrawn; the bootstrap CIs on the PBS candidates (P12) are withdrawn; FROH-adjusted and conditional analyses stand. The submission roadmap in sections 5&ndash;6 has not been revised."],
]
blk = f"""
<h2 style="border-bottom:3px solid #16a34a;">CURRENT STATUS (2026-10-09)</h2>
<div class="box info" style="background:#e3f2fd;border-left:4px solid #1565c0;padding:13px 17px;margin:12px 0;border-radius:8px">Everything quantitative in the population-genetics steps now rests on the NYGC 30x GRCh38 reference and the expanded cohort of 1,256 samples. Summary: Uzbeks are about 50% EUR-like, 30% EAS-like, 19% SAS-like at K=4 (a number that depends on K and on a reference panel without Central Asian groups); F<sub>ST</sub> to SAS and EUR is about 0.014&ndash;0.015, to EAS 0.040, to AFR 0.131; no PBS candidate; median F<sub>ROH</sub> 0.0147. Sections 1&ndash;3 below describe deprecated old runs and are kept for the record; sections 4&ndash;6 concern the RPL GWAS roadmap and were not revised except where noted.</div>
{table(["Item", "Status", "Detail"], rows)}
"""
t = put(t, "next", blk, replace_range=('<h2 style="border-bottom:3px solid #16a34a;">CURRENT STATUS (2026-10-02)</h2>', '<h2 style="color:#991b1b;">1. Current Status Summary</h2>'))
# withdrawn marks inside the old roadmap
t = t.replace("Bootstrap CIs on the 5 corrected PBS candidates (1,000 resamples)", "[WITHDRAWN 2026-10-04: candidates were reference-file artefacts] Bootstrap CIs on the 5 corrected PBS candidates (1,000 resamples)")
t = t.replace("ARG methods (ARG-Needle genealogical corroboration for PBS candidates)", "ARG methods (ARG-Needle; corroborating PBS candidates is withdrawn, Ne(t) remains the aim)")
t = banner(t, "<strong>Updated 2026-10-09:</strong> status table rebuilt; two analyses (Kazakh reference, Ne(t)) are not completed because of a server outage. <a href=\"deprecated_old_runs.html\">Current and deprecated runs</a>.")
write("steps/next_steps.html", t)
print("next ok")
